<?php
/**
 * Created by PhpStorm.
 * User: ADMIN
 * Date: 11/24/2017
 * Time: 4:06 PM
 */

namespace Magento\Storepickup\Test\Block\Adminhtml\Schedule;

use Magento\Storepickup\Test\Block\Adminhtml\StorepickupGrid;

/**
 * Class ScheduleGrid
 * @package Magento\Storepickup\Test\Block\Adminhtml\Schedule
 */
class ScheduleGrid extends StorepickupGrid
{
    protected $filters = [
        'id' => [
            'selector' => '[name="schedule_id[from]"]'
        ],
        'name' => [
            'selector' => '[name="schedule_name"]'
        ]
    ];

    public function resetFilter()
    {
        $this->waitLoader();
        parent::resetFilter(); // TODO: Change the autogenerated stub
    }
}